[workspace]
members = [
    "first_word",
    "integral",
    "last_word",
    "longman",
    "pop",
    "speedometer",
    "tumba-umba",
]
exclude = [
    "mytest",
    "for_lesson",
]

[profile.dev.package.speedometer]
debug = false
