[workspace]
members = [
    "first_word",
    "integral",
    "last_word",
    "longman",
    "pop",
    "speedometer",
    "tumba-umba",
    "mcko",
    "sfml_apps/*",
    "resheto",
    "mask1",
    "probnik",
]
exclude = [
    "mytest",
    "for_lesson",
]
resolver = "2"

[profile.dev.package.speedometer]
debug = false
