[workspace]
members = [
    "first_word",
    "integral",
    "last_word",
    "longman",
    "pop",
    "speedometer",
    "tumba-umba",
    "mcko",
    "sfml_apps/*",
]
exclude = [
    "mytest",
    "for_lesson",
]
resolver = "2"

[profile.dev.package.speedometer]
debug = false # as I see it doesn't work and I don't know what to do with this
