line-length = 100
target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "ANN204",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D205",
    "D213",
    "INP001",
    "ISC001",
    "N801",
    "N802",
    "PLR2004",
    "RUF002",
    "S101",
    "S311",
    "T201",
]

[lint.per-file-ignores]
"Rn*" = ["ALL"]
"Poly*" = ["ALL"]
"Matrix*" = ["ALL"]
