[package]
name = "integral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = "0.2.6"
meval = { git = "https://github.com/Titaniumtown/meval-rs" }
