name: C++ compile

on:
  push:
    paths:
      - '**.cpp'
  pull_request:
    paths:
      - '**.cpp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clang
        run: sudo apt-get install clang
      - name: Compile files
        run: |
          for file in $(git diff --name-only HEAD~1); do
            clang++ $file
          done
