name: CI-py

on:
  workflow_dispatch:
  push:
    paths: ['**.py', '**/py.yml', 'Makefile']
  pull_request:
    paths: ['**.rs', '**/py.yml', 'Makefile']

jobs:
  build:
    name: check python files
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: compile all files
        run: |
          pip install pipx
          make py
      - uses: chartboost/ruff-action@v1
        with:
          src: "./pie"
      - name: run speedometers
        run: |
          time python pie/speedometer.py
          time python pie/numbed.py
