name: CI-py

on:
  workflow_dispatch:
  push:
    paths: ['**.py', '**/py.yml', 'meson.build', 'pie/meson.build']
  pull_request:
    paths: ['**.py', '**/py.yml', 'meson.build', 'pie/meson.build']

jobs:
  build:
    name: check python files
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: compile all files
        run: |
          brew install meson
          pip install -r pie/requirements.txt
          meson setup -Dbuild_py=true build
          meson install -C build --destdir=build/dummy
      - uses: chartboost/ruff-action@v1
        with:
          src: "./pie"
      - name: run speedometers
        run: |
          time python pie/speedometer.py
          time python pie/numbed.py
