name: CI-py

on:
  workflow_dispatch:
  push:
    paths: ["**.py", "**/py.yml", "meson.build", "pie/meson.build"]
  pull_request:
    paths: ["**.py", "**/py.yml", "meson.build", "pie/meson.build"]

jobs:
  build:
    name: check python files
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ucrt64
          pacboy: >-
            meson
            python-numba
            python-matplotlib
      - name: compile all files
        run: |
          meson setup -Dbuild_py=true -Dpython.bytecompile=1 build
          meson install -C build --destdir=build/dummy
      - uses: chartboost/ruff-action@v1
        with:
          src: "./pie"
      - name: run speedometers
        run: |
          time python pie/speedometer.py
          time python pie/numbed.py
