name: Cargo Build & Test

on:
  push:
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Test Rust project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
