name: CI-rust

on:
  push:
    paths:
      '**.rs'
  pull_requests:
    paths:
      '**.rs'

jobs:
  build:
    name: build with latest rust
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: fish
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: update to $ {{ matrix.toolchain }} rust
        run: rustup update ${{ matrix.toolchain }} ; rustup default $${{ matrix.toolchain }}
      - name: build workspace
        run: cd rusted ; cargo b -v
