name: CI-rust

on:
  workflow_dispatch:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', '**/meson.build']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', '**/meson.build']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native'

jobs:
  build:
    name: check with latest rust
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: clang64
          pacboy: >-
            gcc:p
            meson:p
            rust:p
            sfml:p
      - name: build rust files
        run: |
          meson setup -Dbuild_rust=true build
          meson compile -C build
