name: CI-rust

on:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check with latest rust
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: update to ${{ matrix.toolchain }} rust
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt clippy
      - name: install sfml
        run: sudo apt-get install sfml csfml
      - name: build workspace
        run: cd rusted && cargo b -v
      - name: fmt and clippy check
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cd rusted && cargo fmt -- --check && cargo clippy -- -D warnings
