name: CI-rust

on:
  workflow_dispatch:
  push:
    paths: ["**.rs", "**.toml", "**.lock", "**/rust.yml", "meson.build", "rusted/meson.build"]
  pull_request:
    paths: ["**.rs", "**.toml", "**.lock", "**/rust.yml", "meson.build", "rusted/meson.build"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    name: check with latest rust
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ucrt64
          pacboy: >-
            rust
            cc
            meson
            cmake
            ninja
            freetype
            libvorbis
            sfml
            git:
      - name: build rust files
        env:
          CMAKE_GENERATOR: "Ninja"
        run: |
          meson setup -Dbuild_rust=true -Dci_env=true build
          meson compile -C build
