name: CI-rust

on:
  workflow_dispatch:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', 'rusted/meson.build']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', 'rusted/meson.build']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native'

jobs:
  build:
    name: check with latest rust
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: clang64
          pacboy: >-
            rust:p
            sfml:p
            gcc:p
      - name: build rust files
        run: cargo build -v --manifest-path rusted/Cargo.toml
      - name: clippy and fmt check
        run: |
          cd rusted
          cargo fmt -- --check && cargo clippy -- -D warnings
