name: CI-rust

on:
  workflow_dispatch:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', 'rusted/meson.build']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/rust.yml', 'meson.build', 'rusted/meson.build']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native'

jobs:
  build:
    name: check with latest rust
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: update to ${{ matrix.toolchain }} rust and install deps
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt clippy
          brew install meson sfml
      - name: build rust files
        run: |
          meson setup -Dbuild_rust_all=true build && meson compile -C build
      - name: clippy and fmt check
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo fmt -- --check && cargo clippy -- -D warnings
