name: Cargo Build & Test

on:
  push:
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Test Rust project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Get list of changed files
        id: get-changes
        run: echo "changes=$(git diff --name-only HEAD $(git merge-base HEAD master))" >> $GITHUB_STATE
      - name: Extract project names from changed files
        id: extract-projects
        run: echo "projects=$(echo ${{ steps.get-changes.outputs.changes }} | grep -oE 'rusted/([^/]+)/' | cut -d'/' -f2- | sort | uniq)"
      - name: Install Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build and test changed projects
        run: |
          for project in ${{ steps.extract-projects.outputs.projects }}; do
            cd ${{ github.workspace }}/rusted/$project
            cargo build --verbose
            cargo test --verbose
          done
