name: CI-rust

on:
  push:
    paths:
      '**.cpp'
      '**.c'
  pull_requests:
    paths:
      '**.cpp'
      '**.c'

jobs:
  build:
    name: build with latest rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: update to $ {{ matrix.toolchain }} rust
        run: rustup update ${{ matrix.toolchain }} && rustup default $${{ matrix.toolchain }}
      - name: build workspace
        run: cargo b -v
