name: test code

on:
  workflow_dispatch:
  push:
    paths: ["**.rs", "**.toml", "**.lock", "**.yml", "**.c*", "**.py", "**.h*", "**.build"]
  pull_request:
    paths: ["**.rs", "**.toml", "**.lock", "**.yml", "**.c*", "**.py", "**.h*", "**.build"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  test:
    name: test all the code
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: msys2/setup-msys2@cafece8e6baf9247cf9b1bf95097b0b983cc558d # v2.31.0
        with:
          update: true
          msystem: ucrt64
          pacboy: >-
            rust
            cc
            meson
            cmake
            ninja
            freetype
            libvorbis
            sfml
            python-numba
            python-matplotlib
            git:
      - name: test
        env:
          CMAKE_GENERATOR: "Ninja"
        run: |
          meson setup -Dbuild_all=true -Dtests=true -Dci_env=true build
          meson compile -C build
          meson test -C build
