name: test code

on:
  workflow_dispatch:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**.yml', '**.c*', '**.py', '**.h*', '**/meson.build']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**.yml', '**.c*', '**.py', '**.h*', '**/meson.build']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native'

jobs:
  test:
    name: test all the code
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANG64
          pacboy: >-
            gcc:p
            meson:p
            rust:p
            sfml:p
      - name: test
        run: |
          cd pie && python3 mcko.py && cd ..
          cargo test --locked --manifest-path rusted/Cargo.toml
          meson setup -Dbuild_c_cpp=true build && meson compile -C build
          ./build/dad-is-great-in-C/ogntest
