name: test code

on:
  workflow_dispatch:
  push:
    paths: ["**.rs", "**.toml", "**.lock", "**.yml", "**.c*", "**.py", "**.h*", "**.build"]
  pull_request:
    paths: ["**.rs", "**.toml", "**.lock", "**.yml", "**.c*", "**.py", "**.h*", "**.build"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  test:
    name: test all the code
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: clang64
          pacboy: >-
            meson
            rust
            python-numba
            git:
      - name: test
        run: |
          cd pie && python3 mcko.py && cd ..
          meson setup -Dbuild_all=true -Dtests=true build
          meson compile -C build
          meson test -C build
