name: test code

on:
  workflow_dispatch:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**.yml', '**.c*', '**.py', '**.h*', '**/meson.build']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**.yml', '**.c*', '**.py', '**.h*', '**/meson.build']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native -Zmacro-backtrace -Zthreads=3'

jobs:
  test:
    name: test all the code
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: default to nightly rust and download deps
        run: |
          rustup update nightly
          rustup default nightly
          brew install meson
          cd pie && pip install -r requirements.txt
      - name: test
        run: |
          python3 pie/mcko.py
          cargo test --locked --manifest-path rusted/Cargo.toml
          meson setup -Dbuild_c_cpp=true build && meson compile -C build
          ./build/dad-is-great-in-C/ogntest
